apiVersion: "spec.keptn.sh/0.2.3"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "stage"
      sequences:
        - name: "delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
            - name: "test"
              properties:
                teststrategy: "performance"
            - name: "evaluation"
    - name: "preprod"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "stage.delivery.finished"
          tasks:
            - name: "approval"
              properties:
                pass: "automatic"
                warning: "manual"
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"

